import os
import subprocess
import tempfile

STUDENTS_DIR = 'students'
OUTPUT_JS = 'strudel_bundle.js'

IMAGES = [
    'https://th.bing.com/th/id/OIP.2stYdpfk62fcRZIl9Lr3HAHaFW?rs=1&pid=ImgDetMain',
    'https://th.bing.com/th/id/OIP.PtTWJAKDjQS-02KNcxEEJAAAAA?rs=1&pid=ImgDetMain',
    'https://upload.wikimedia.org/wikipedia/commons/a/ad/Ada_lovelace_10k_31i.png',
    'https://upload.wikimedia.org/wikipedia/commons/0/0e/Analog_Computing_Machine_GPN-2000-000354.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/6/65/%27bombe%27.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/2/24/Women_holding_parts_of_the_first_four_Army_computers.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/5/5d/Charles-babbage.intel.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/5/5c/Bombe-rebuild.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/f/f8/Alan_Turing_%281951%29.jpg',
    'https://static.independent.co.uk/s3fs-public/thumbnails/image/2020/03/01/12/katherine-johnson.jpg',
    'https://upload.wikimedia.org/wikipedia/commons/6/62/Katherine_Johnson_at_NASA%2C_in_1966.jpg',
]

TEMPLATE = """await initHydra();

function getRandomInt(max) {{
  return Math.floor(Math.random() * max);
}};

var aImages = {images};

var STUDENT_SNIPPETS = {snippets};

var SWAP_INTERVAL_MS = 30000;

function loadRandomSnippet() {{
  aImages.sort(function () {{ return Math.random() - 0.5; }});
  s0.initImage(aImages.pop());
  s1.initImage(aImages.pop());
  s2.initImage(aImages.pop());

  var chosen = STUDENT_SNIPPETS[getRandomInt(STUDENT_SNIPPETS.length)];
  try {{
    eval(chosen.code);
  }} catch (e) {{
    console.error('Error executing script:', chosen.file, e);
  }}
}}

loadRandomSnippet();
setInterval(loadRandomSnippet, SWAP_INTERVAL_MS);
"""

HEADER = (
    "// Auto-generated by build_strudel_bundle.py - do not edit by hand\n"
    "// Paste this entire file into the strudel.cc code editor and run it.\n"
)


def js_string_literal(s):
    escaped = (
        s.replace('\\', '\\\\')
        .replace("'", "\\'")
        .replace('\n', '\\n')
        .replace('\r', '')
    )
    return "'" + escaped + "'"


def minify(source):
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False) as tmp:
        tmp.write(source)
        tmp_path = tmp.name
    try:
        result = subprocess.run(
            ['npx', '--yes', 'terser', tmp_path, '--compress', '--mangle', '--module',
             '--format', 'quote_style=1'],
            capture_output=True, text=True, check=True,
        )
        return result.stdout
    finally:
        os.remove(tmp_path)


def main():
    fnames = sorted(f for f in os.listdir(STUDENTS_DIR) if f.endswith('.js'))
    entries = []
    for fname in fnames:
        path = f"{STUDENTS_DIR}/{fname}"
        with open(path, 'r') as f:
            code = f.read()
        entries.append({"file": path, "code": code})

    images_js = "[\n" + ",\n".join("  " + js_string_literal(url) for url in IMAGES) + "\n]"
    snippets_js = "[\n" + ",\n".join(
        "  { file: %s, code: %s }" % (js_string_literal(e["file"]), js_string_literal(e["code"]))
        for e in entries
    ) + "\n]"

    source = TEMPLATE.format(
        images=images_js,
        snippets=snippets_js,
    )

    minified = minify(source)

    with open(OUTPUT_JS, 'w') as f:
        f.write(HEADER + minified)

    print(f"Wrote {OUTPUT_JS} with {len(entries)} student snippets (minified).")


if __name__ == '__main__':
    main()
