import os
import json

STUDENTS_DIR = 'students'
OUTPUT_JS = 'students_bundle.js'

def main():
    fnames = sorted(f for f in os.listdir(STUDENTS_DIR) if f.endswith('.js'))
    entries = []
    for fname in fnames:
        path = f"{STUDENTS_DIR}/{fname}"
        with open(path, 'r') as f:
            code = f.read()
        entries.append({"file": path, "code": code})

    with open(OUTPUT_JS, 'w') as f:
        f.write("// Auto-generated by build_students_bundle.py - do not edit by hand\n")
        f.write("window.STUDENT_SNIPPETS = ")
        json.dump(entries, f, indent=2)
        f.write(";\n")

    print(f"Wrote {OUTPUT_JS} with {len(entries)} student snippets.")

if __name__ == '__main__':
    main()
